[package]
name = "bevy_transform_gizmo"
version = "0.1.0"
authors = ["Aevyrie Roessler <aevyrie@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_mod_picking = { git = "https://github.com/JulianRuiseco/bevy_mod_picking", rev = "d0e9baf67b316d3b0c38870f95ef0c4c173db1c9" }
bevy_mod_raycast = { git = "https://github.com/JulianRuiseco/bevy_mod_raycast", rev="ab786bcd3ad4117d3b13ef7f2379c020611014ac" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", version = "0.5", default-features = false, features = [
    "render",
    "bevy_wgpu",
    "bevy_winit",
    "bevy_gltf",
    "x11",
    "jpeg",
] }
