[package]
name = "bevy_transform_gizmo"
version = "0.1.0"
authors = ["Aevyrie Roessler <aevyrie@gmail.com>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", default-features = false, features = ["render"] }
bevy_mod_picking = "0.5"
bevy_mod_raycast = "0.3"

[dependencies.naga]
features = ["wgsl-in", "spv-out", "wgsl-out"]
version = "*"

[dev-dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "bevy_winit",
    "x11",
] }
