[package]
name = "bevy_transform_gizmo"
version = "0.1.0"
authors = ["Aevyrie Roessler <aevyrie@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", default-features = false, features = ["render"] }
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", branch = "master" }
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast", branch = "master" }

[dependencies.naga]
features = ["wgsl-in", "spv-out", "wgsl-out"]
version = "*"

[dev-dependencies]
bevy = { version = "0.6", default-features = false, features = ["bevy_winit"] }
